language: python
python:
  - "3.4"
  - "3.5"

install:
  - pip install flake8
  - pip install pytest
  - pip install coverage
  - pip install coveralls
  - python setup.py install
  
script: 
  - py.test
  - flake8 --max-line-length=100 asyncio_dispatch
  - run --source asyncio_dispatch -m py.test

after_success:
  - coveralls